[vs_day_1]
name = "Radar Training"
day = "Sunday"
tasks = [
    "Use 1 Stamina",
    "Complete 1 Radar task",
    "Use at least 660 Hero EXP",
    "Use 1 Drone Combat Data point",
    "Use 1 Drone Part",
    "Use Drone Skill Chip",
    "Gather 100 Food (Radar mining tasks do not count)",
    "Gather 100 Iron (Radar mining tasks do not count)",
    "Gather 60 Gold (Radar mining tasks do not count)",
]
arms_race = ["Drone Boost: Save drone upgrade and stamina burn for the following day 9:00 AM EST.",
             "Hero Advancement: Save hero exp for the following day 1:00 PM EST"]

[vs_day_2]
name = "Base Expansion"
day = "Monday"
tasks = [
    "Use 1-min Construction Speedup",
    "Increase Building by 1pt",
    "Dispatch UR Trade Truck 1 time",
    "Perform 1 Legendary Secret Task",
    "Recruit Survivor 1 time",
]
arms_race = ["City Building at 1:00 AM EST"]

[vs_day_3]
name = "Age of Science"
day = "Tuesday"
tasks = [
    "Use 1-min Research Speedup",
    "Increase Tech Power by 1pt",
    "Use 1 Valor Badge",
    "Complete 1 Radar task",
    "For each Lv. 1 - 10 Drone Component Chest opened",
]
arms_race = ["Tech Research at 5:00 AM EST",
             "Drone Boost: burn stamina for radar tasks at 9:00 AM EST"]


[vs_day_4]
name = "Train Heroes"
day = "Wednesday"
tasks = [
    "Elite Recruit 1 time",
    "Use at least 660 Hero EXP",
    "Use 1 Legendary Hero Shard",
    "Use 1 Epic Hero Shard",
    "Use 1 Rare Hero Shard",
    "Use 1 Skill Medal",
    "Use"
]
arms_race = ["Hero Advancement: Save exp and hero tickets for 9:00 AM EST"]


[vs_day_5]
name = "Total Mobilization"
day = "Thursday"
tasks = [
    "Complete 1 Radar task",
    "Use 1-min Construction Speedup",
    "Increase Building by 1pt",
    "Use 1-min Research Speedup",
    "Increase Tech Power by 1pt",
    "Use 1-min Training Speedup",
    "Train any Lv. 1 to 10 unit",

]
arms_race = ["Tech Research at 9:00 PM EST","City Building at 9:00 AM EST","Unit Progression: build troops at 1:00PM EST"]


[vs_day_6]
name = "Enemy Buster"
day = "Friday"
tasks = [
    "Use 1-min Construction Speedup",
    "Use 1-min Research Speedup",
    "Use 1-min Training Speedup",
    "Use 1-min Healing Speedup",
    "Every Lv. 1 to 10 Unit Killed from rival Alliance",
    "Every Lv. 1 to 10 Unit Killed",
    "Every Lv. 1 to 10 Unit Lost",
]
arms_race = ["None"]

[vs_day_7]
name = "Day after tomato"
day = "Saturday"
tasks = ["No tasks"]
arms_race = ["None"]
